### ISSUE TITLE
event cannot be created

### ISSUE THREAD

**Issue by Apfelwurm** [Lan2Play/NetEvent#275]
```
fail: NetEvent.Client.Services.EventService[0]
      Unable to create event in backend.
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NetEvent.Client.Services.EventService.CreateEventAsync(EventDto eventDto, CancellationToken cancellationToken)
```

**Comment by Apfelwurm** [comment]
Admin.Images.Write
Admin.Events.Write
Admin.Venues.Write

Are not assigned by default to the admin role

**Comment by Apfelwurm** [comment]
venue write permission seems not to affect anything at the moment and so unauthorized can write there
image permissions seem not to affect anything at the moment
